/*************************************************************************
 *
 * Compliant Enterprise Logging
 *
 * Declarations for integers representing source file paths
 *
 ************************************************************************/

#pragma once
#ifndef __CELOG2_CELOG_FILEPATHDEFS_H__
#define __CELOG2_CELOG_FILEPATHDEFS_H__



typedef enum
{
  /* CELog2 itself */
  CELOG_FILEPATH_CELOG2_MIN = 0,
  CELOG_FILEPATH_SOURCES_COMMON_CELOG2_TEST_CELOG_TEST_CPP,
  
  /* RMCCore */
  CELOG_FILEPATH_RMCCORE_MIN = 100,
  CELOG_FILEPATH_SOURCES_RMCCORE_RMCCORE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_STDAFX_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_BASE_CORECONST_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_BASE_COREINIT_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_CRYPTO_AES_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_CRYPTO_CRYPTO_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_CRYPTO_DH_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_CRYPTO_MD5_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_CRYPTO_RSA_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_CRYPTO_SHA_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_FORMAT_LOCALFILE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_FORMAT_NXLFILE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_FORMAT_NXLPOLICY_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_NETWORK_HTTPCLIENT_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_NETWORK_HTTPCONST_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_POLICY_CONDITION_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_POLICY_OBLIGATION_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMACTIVITYLOG_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMCERTIFICATE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMCLASSIFICATION_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMHEARTBEAT_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMHTTPREQUEST_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMMEMBERSHIP_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMMYDRIVE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMNXLFILE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMPRODUCT_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMPROJECT_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMPROJECTFILE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMRECIPIENTS_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMSHAREDWORKSPACE_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMSYSPARA_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMTENANT_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMTOKEN_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_RESTFUL_RMUSER_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_UTILS_BASE64_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_UTILS_CRC_CPP,
  CELOG_FILEPATH_SOURCES_RMCCORE_UTILS_NXTIME_CPP,

  /* RMDSDK */
  CELOG_FILEPATH_RMDSDK_MIN = 200,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_REGISTRYSERVICEENTRY_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDLAPI_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRFILES_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRMCINSTANCE_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRMLOGINHTTPREQUEST_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRMNXLFILE_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRMTENANT_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRMUSER_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRNXLTOKEN_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRPARTIALDOWNLOAD_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_SDRSECUREFILE_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_STDAFX_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_COMMON_STRINGEX_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_CRYPT_AES_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_CRYPT_BASIC_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_CRYPT_CERT_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_CRYPT_MD5_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_CRYPT_PROVIDER_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_CRYPT_SHA_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_NETWORK_HTTPCLIENT_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_PDP_PDP_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_RPM_DRVCOREMGR_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_WINUTIL_HOST_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_WINUTIL_KEYM_CPP,
  CELOG_FILEPATH_SOURCES_SDWL_SDWRMCLIB_WINUTIL_SECUREFILE_CPP,
} celog_filepathint_t;



#endif /* __CELOG2_CELOG_FILEPATHDEFS_H__ */
